### ISSUE TITLE
Where is the facade? 🪨 

### ISSUE THREAD

**Issue by andy2great** [MeatCow/ngrx-in-a-nutshell#1]
I think there can be optimisation :rocket:

Since I was born I've always been using facade in angular 18.0 
BRUH... With this, I forgot to look at my facade and was stuck for 20h not knowing why I can't start an action...

Could you remind me to look at the facade please?

**Comment by matthieupauze** [comment]
Wow, this is too true. We can add data-services, services, and facades!

What a good opportunity 😊 💯!

**Comment by matthieupauze** [comment]
Fixed and closed ;)
